### ISSUE TITLE
Static Web APP deployment

### ISSUE THREAD

**Issue by SeryioGonzalez** [Azure-Samples/azure-search-python-samples#108]
In the README, there is a step by step description on how to deploy a Static Web APP from Visual Studio Code using the respective plug-in. The order has been updated in the plugin for static website creation, hence the description in the repo is outdated

**Comment by HeidiSteen** [comment]
Thanks, we revisited that sample and decided to go a different route.  We kept bulk-insert and the azure function for python devs, but standardized on C# for the main tutorial and comprehensive sample.  The updated C# sample is here:  https://github.com/Azure-Samples/azure-search-static-web-app
