### ISSUE TITLE
Error loading the PythonTutorial-AzureSearch-AIEnrichment.ipynb 

### ISSUE THREAD

**Issue by woutvanduffelspks** [Azure-Samples/azure-search-python-samples#39]
There is an issue with the file PythonTutorial-AzureSearch-AIEnrichment.ipynb
The json is not valid. I fixed it locally ( issue is on line 49 in the file), but you might want to fix it for others

Cheers !

**Comment by HeidiSteen** [comment]
This issue has been fixed. Thanks for filing the issue!
