### ISSUE TITLE
A resource without a type name was found,

### ISSUE THREAD

**Issue by Farhad-Heybati** [Azure-Samples/azure-search-python-samples#47]
r = requests.post(construct_Url(search_service, "indexers", None, None, api_version), data=json.dumps(indexer_def),  headers=headers)
<Response [400]>
{
  "error": {
    "code": "",
    "message": "The request is invalid. Details: indexer : A resource without a type name was found, but no expected type was specified. To allow entries without type information, the expected type must also be specified when the model is specified.\r\n"
  }
}

**Comment by HeidiSteen** [comment]
This is a strange error.  I can't repro this, but I know that if there were issues upstream, this step won't work.  If I get 400, it's usually due to something unrelated to the indexer itself, like a skillset issue.
